### ISSUE TITLE
touch and mouse/keyboard devices only seem to support mouse/keyboard scrolling

### ISSUE THREAD

**Issue by SilVdB** [mdbootstrap/perfect-scrollbar#406]
It seems that on devices with both touch and mouse/keyboard support (like the Dell Lattitude E5540), the scrolling with touch doesn't work (in Firefox, in Chrome and IE it does seem to work)

Could this have something to do with automatic detection of touch vs. mouse/keyboard, or is it something we're doing wrong?

**Comment by alotov-agina** [comment]
Having the exact same problem here, with some Windows 10 convertible, supporting touch and touchpad-input.

**Comment by iver56** [comment]
In my case touch scrolling (on a win10 laptop with touch) works in Chrome, Opera and IE11, but not in Edge and Firefox. The problem with Edge seems to have been fixed by https://github.com/noraesae/perfect-scrollbar/pull/401 which is not released at the moment

**Comment by DanielApt** [comment]
As of release `v0.6.10` #401 has fixed. I do however understand this is still an issue in Edge and Firefox.

I don't have a device to reproduce or tackle this bug, anyone able to contribute?

**Comment by closebang** [comment]
Since Firefox 24, Mozilla turn off the the touch event api for the desktop browser.

https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#Browser_compatibility

**Comment by noraesae** [comment]
Not sure if it's still an issue. Any further problem?

**Comment by Maximaximum** [comment]
Perfect scrollbar does not seem to work with touch emulation in Google Dev Tools. Is this a Google DevTools bug, or a Perfect scrollbar bug?

**Comment by jaykyburz** [comment]
In firefox 48.0.1 on a Surface Pro 3, I can touch the scrollbars and drag touch the actual bar to scroll, but touch dragging the content of the element doesn't seem to work.
