### ISSUE TITLE
Perfect scrollbar doesn't work on Chrome ( laptop with a touch screen ) 

### ISSUE THREAD

**Issue by pglejzer** [mdbootstrap/perfect-scrollbar#867]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [x] Provide a page or source code where the issue can be checked - https://mdbootstrap.com/

Perfect scrollbar doesn't work on Chrome 74.0.3729.131 on laptops with a touch screen. It doesn't even work on your demo page http://utatti.github.io/perfect-scrollbar/ .

**Comment by LancerComet** [comment]
The temporary solution:
```
if (typeof window['DocumentTouch'] === 'undefined') {
  window['DocumentTouch'] = HTMLDocument
}
```
Works in Chrome + Thinkpad X1E

**Comment by IulianParaian** [comment]
> The temporary solution:
> 
> ```
> if (typeof window['DocumentTouch'] === 'undefined') {
>   window['DocumentTouch'] = HTMLDocument
> }
> ```
> 
> Works in Chrome + Thinkpad X1E

This fix is working for me. Thanks

**Comment by imsam67** [comment]
I'm having the same issue in my React app that uses `perfect-scrollbar`.

**Comment by dylan904** [comment]
> The temporary solution:
> 
> ```
> if (typeof window['DocumentTouch'] === 'undefined') {
>   window['DocumentTouch'] = HTMLDocument
> }
> ```
> 
> Works in Chrome + Thinkpad X1E

Didn't work for me, Chrome + Chromebook

**Comment by DavidMarquezF** [comment]
I think this was solved with PR #829, which was merged but is not released yet

**Comment by imsam67** [comment]
@DavidMarquezF Any idea when it will be released?

**Comment by DavidMarquezF** [comment]
Nope, I just found the pull request trying to find a solution. This repository seems pretty dead (last version was uploaded to npm 1 year ago), so maybe the best solution is to npm install the master branch

**Comment by imsam67** [comment]
I'm pretty much done with `perfect scrollbar`. It's clear to me that it's time to move on!

**Comment by DavidMarquezF** [comment]
If you find any good alternative let us know @imsam67!

**Comment by imsam67** [comment]
@DavidMarquezF I will. You do the same please!

**Comment by mattonit** [comment]
Fixed in #829

**Comment by bagaskarala** [comment]
In my app, suddenly perfect scrollbar doesn't work in touch devices in chrome. I'm using perfect-scrollbar 1.5.0 and using vue-perfect-scrollbar 0.2.1. I don't change anything about this source code since the past year, but it now doesn't work if i scroll in touch device, only work using mouse scroll. How to fix this?

**Comment by egd-flaine** [comment]
Still facing this issue on Chrome and Firefox (both with latest version).  It's working fin on Edge.

I'm using the latest version of perfect-scrollbar.
Do you have any fix or information to help me ?

In advance, thanks a lot.

Fred
